#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# normalize_path VALUE prints VALUE cleaned for use as a filesystem path:
# surrounding whitespace and one pair of surrounding quotes stripped, a leading
# ~ expanded, and under Git Bash/Cygwin a Windows form (D:\... or D:/...)
# converted to POSIX form so [[ -f ]] works. POSIX paths pass through as-is.
normalize_path() {
  local p="$1"
  p="${p#"${p%%[![:space:]]*}"}"
  p="${p%"${p##*[![:space:]]}"}"
  if [[ ${#p} -ge 2 ]]; then
    local first="${p:0:1}" last="${p: -1}"
    if { [[ "$first" == '"' && "$last" == '"' ]] || [[ "$first" == "'" && "$last" == "'" ]]; }; then
      p="${p:1:${#p}-2}"
    fi
  fi
  if [[ "$p" == "~" ]]; then
    p="$HOME"
  elif [[ "$p" == "~/"* ]]; then
    p="$HOME/${p#\~/}"
  fi
  if command -v cygpath >/dev/null 2>&1 && [[ "$p" =~ ^[A-Za-z]:[\\/] ]]; then
    p=$(cygpath -m "$p")
  fi
  printf '%s' "$p"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

banner "ignition-runtime-bundle deployment"

# ── Wizard-specific constants and helpers ────────────────────────────────
# Pinned MCP Module (tests/fixtures/modules/MCP-module-*.provenance.json).
MODULE_BUILD="2026021307"
MODULE_SHA256="b1142a5796f2fd834555f13f03de706599d745f7172a68e54f2f7908b67fe365"
TOKEN_FILE="$HOME/.config/ignition-mcp/gateway.token"

# Every setup-native call goes through here with stdin closed, so the CLI
# can never consume the wizard's prompt input.
run_cli() {
  uv run --package ignition-rest-mcp ignition-mcp setup-native "$@" </dev/null
}

# ── Stage 1: prerequisites ───────────────────────────────────────────────
stage "Prerequisites"
say "Deploys the ignition-runtime-bundle to an Ignition Gateway:"
note "  build release → install MCP Module → parameters → policy → doctor → plan → apply → verify"
if ! command -v uv >/dev/null 2>&1; then
  warn "uv is not on PATH (install: https://docs.astral.sh/uv/)"
  exit 1
fi
if ! command -v git >/dev/null 2>&1; then
  warn "git is not on PATH"
  exit 1
fi
REPO_ROOT=""
d="$PWD"
while [[ -n "$d" && "$d" != "/" ]]; do
  if [[ -f "$d/packages/ignition-runtime-bundle/BUNDLE_VERSION" && -f "$d/tooling/native/cli.py" ]]; then
    REPO_ROOT="$d"
    break
  fi
  d=$(dirname "$d")
done
if [[ -z "$REPO_ROOT" ]]; then
  ask REPO_ROOT "Path to the ignition-mcp checkout:"
  if [[ -n "$REPO_ROOT" ]]; then REPO_ROOT=$(cd "$REPO_ROOT" 2>/dev/null && pwd) || REPO_ROOT=""; fi
fi
if [[ -z "$REPO_ROOT" || ! -f "$REPO_ROOT/packages/ignition-runtime-bundle/BUNDLE_VERSION" ]]; then
  warn "could not find an ignition-mcp checkout (need packages/ignition-runtime-bundle/BUNDLE_VERSION)"
  exit 1
fi
cd "$REPO_ROOT"
note "checkout: $REPO_ROOT"
note "bundle version: $(cat packages/ignition-runtime-bundle/BUNDLE_VERSION)"
pause "Press Enter to continue"

# ── Stage 2: Gateway connection ──────────────────────────────────────────
stage "Gateway connection"
say "Point the wizard at your Gateway and capture the API token."
while :; do
  ask GATEWAY_URL "Gateway base URL (e.g. http://127.0.0.1:8088):"
  if [[ "$GATEWAY_URL" =~ ^https?://[^/@]+(:[0-9]+)?(/.*)?$ ]]; then
    break
  fi
  warn "use an absolute http(s) URL with a host, no embedded credentials"
done
write_env GATEWAY_URL "$GATEWAY_URL"
export IGNITION_MCP_SETUP_GATEWAY_URL="$GATEWAY_URL"
TOKEN_FILE_OK=0
if [[ -f "$TOKEN_FILE" && ! -L "$TOKEN_FILE" ]] && [[ "$(wc -l < "$TOKEN_FILE")" -eq 1 ]]; then
  TOKEN_FILE_OK=1
fi
if (( TOKEN_FILE_OK )) && ! confirm "Replace the existing token file ($TOKEN_FILE)?"; then
  note "keeping the existing token file"
else
  say "Create the token in the Ignition web UI (Gateway → Security → API Tokens),"
  note "give it read access, then paste it below. It is stored only in $TOKEN_FILE (mode 0600)."
  ask_secret GATEWAY_TOKEN "Ignition API token:"
  if [[ -z "$GATEWAY_TOKEN" ]]; then
    warn "no token given"
    exit 1
  fi
  mkdir -p "$(dirname "$TOKEN_FILE")"
  ( umask 077; printf '%s\n' "$GATEWAY_TOKEN" > "$TOKEN_FILE" )
  chmod 0600 "$TOKEN_FILE"
  note "token written to $TOKEN_FILE (mode 0600, one line)"
fi

# ── Stage 3: build the bundle release ────────────────────────────────────
stage "Build the bundle release"
say "Validating the Designer project and building deterministic release artifacts."
uv run --no-sync python -m tooling.native.cli validate --project-dir packages/ignition-runtime-bundle/project
uv run --no-sync python -m tooling.native.cli release \
  --project-dir packages/ignition-runtime-bundle/project \
  --out-dir dist/release \
  --source-revision "$(git rev-parse HEAD)" \
  --evidence-dir tests/compatibility/evidence
V=$(cat packages/ignition-runtime-bundle/BUNDLE_VERSION)
(cd dist/release && sha256sum -c "ignition-runtime-bundle-$V.sha256")
BUNDLE_MANIFEST="dist/release/ignition-runtime-bundle-$V.manifest.json"
BUNDLE_ZIP="dist/release/ignition-runtime-bundle-$V.zip"
write_env BUNDLE_VERSION "$V"
write_env BUNDLE_MANIFEST "$BUNDLE_MANIFEST"
write_env BUNDLE_ZIP "$BUNDLE_ZIP"
note "release: $BUNDLE_ZIP (checksum verified)"

# ── Stage 4: install the MCP Module ──────────────────────────────────────
stage "Install the MCP Module"
say "The repository pins MCP Module build $MODULE_BUILD (com.inductiveautomation.mcp)."
note "SHA-256: $MODULE_SHA256"
note "Download the .modl from the official Inductive Automation channel if you do not have it."
ask MODL_PATH "Path to the MCP Module .modl file:"
MODL_PATH=$(normalize_path "$MODL_PATH")
if [[ -z "$MODL_PATH" || ! -f "$MODL_PATH" ]]; then
  warn "no such file: ${MODL_PATH:-<empty>}"
  case "$OSTYPE" in
    msys*|cygwin*) note "under Git Bash type the path as Windows shows it (D:\\...) or in POSIX form (/d/...); quotes are stripped" ;;
  esac
  exit 1
fi
actual=$(sha256sum "$MODL_PATH" | awk '{print $1}')
if [[ "$actual" != "$MODULE_SHA256" ]]; then
  warn "local SHA-256 $actual does not match the pinned $MODULE_SHA256"
  warn "install-module would refuse this file; fetch the pinned build and re-run."
  exit 1
fi
write_env MODL_PATH "$MODL_PATH"
if ! confirm "Accept the Module certificate and EULA, and restart the Gateway after install?"; then
  warn "certificate and EULA acceptance are required to install; stopping before any upload."
  exit 1
fi
run_cli install-module \
  --file "$MODL_PATH" \
  --sha256 "$MODULE_SHA256" \
  --gateway-token-file "$TOKEN_FILE" \
  --accept-certificate --accept-eula --restart

# ── Stage 5: deployment parameters ───────────────────────────────────────
stage "Deployment parameters"
say "Identity of the deployment: profile, bundle project and Server Config names."
while :; do
  ask PROFILE "Profile (readonly/operator/configurator/full):"
  case "$PROFILE" in
    readonly|operator|configurator|full) break ;;
    *) warn "unknown profile; choose readonly, operator, configurator or full" ;;
  esac
done
ask BUNDLE_PROJECT "Bundle project name:"
[[ -n "$BUNDLE_PROJECT" ]] || BUNDLE_PROJECT="ignition_runtime"
ask SERVER_CONFIG_NAME "MCP server config name:"
[[ -n "$SERVER_CONFIG_NAME" ]] || SERVER_CONFIG_NAME="production"
ask BACKUP_DIR "Backup directory (the only local copy before overwrites):"
BACKUP_DIR=$(normalize_path "$BACKUP_DIR")
[[ -n "$BACKUP_DIR" ]] || BACKUP_DIR="backups/ignition-mcp"
mkdir -p "$BACKUP_DIR"
ask PERMISSIONS_FILE "Server Config permissions tree file (Enter to skip, '-' clears a saved value):"
PERMISSIONS_FILE=$(normalize_path "$PERMISSIONS_FILE")
if [[ "$PERMISSIONS_FILE" == "-" ]]; then PERMISSIONS_FILE=""; fi
PROVISION_SECURITY_LEVELS=no
if confirm "Provision the dedicated Runtime Security Level (--provision-security-levels)?"; then
  PROVISION_SECURITY_LEVELS=yes
fi
CREATE_RUNTIME_TOKEN=no
RUNTIME_TOKEN_FILE=""
if confirm "Create the Runtime API token (--create-runtime-token)?"; then
  CREATE_RUNTIME_TOKEN=yes
  ask RUNTIME_TOKEN_FILE "Where to write the created token (mode 0600):"
  RUNTIME_TOKEN_FILE=$(normalize_path "$RUNTIME_TOKEN_FILE")
  [[ -n "$RUNTIME_TOKEN_FILE" ]] || RUNTIME_TOKEN_FILE="$HOME/.config/ignition-mcp/runtime.token"
fi
write_env PROFILE "$PROFILE"
write_env BUNDLE_PROJECT "$BUNDLE_PROJECT"
write_env SERVER_CONFIG_NAME "$SERVER_CONFIG_NAME"
write_env BACKUP_DIR "$BACKUP_DIR"
if [[ -n "$PERMISSIONS_FILE" ]]; then
  write_env PERMISSIONS_FILE "$PERMISSIONS_FILE"
fi
write_env PROVISION_SECURITY_LEVELS "$PROVISION_SECURITY_LEVELS"
write_env CREATE_RUNTIME_TOKEN "$CREATE_RUNTIME_TOKEN"
if [[ -n "$RUNTIME_TOKEN_FILE" ]]; then
  write_env RUNTIME_TOKEN_FILE "$RUNTIME_TOKEN_FILE"
fi

# ── Stage 6: Runtime Target Policy ───────────────────────────────────────
stage "Runtime Target Policy"
say "The policy document controls which Runtime Mutations are allowed."
ask POLICY_FILE "Runtime Target Policy file:"
POLICY_FILE=$(normalize_path "$POLICY_FILE")
[[ -n "$POLICY_FILE" ]] || POLICY_FILE="policy.json"
if [[ ! -f "$POLICY_FILE" ]]; then
  cat > "$POLICY_FILE" <<'POLICY'
{
  "schemaVersion": 1,
  "serviceIdentity": "ignition-mcp-service",
  "auditMode": "best_effort",
  "auditProfile": "MCP_AUDIT",
  "allowlists": {},
  "alarmShelveMaxSeconds": 3600,
  "tagUpdateMaxItems": 20
}
POLICY
  warn "generated a default $POLICY_FILE with EMPTY allowlists: every Runtime Mutation fails closed"
  note "add targets per Tool name, e.g. \"allowlists\": {\"tag_write\": [\"[default]Plant/AHU\"]}"
  note "shape and rules: docs/operations/runbook.md, section 'The Runtime Target Policy'"
fi
write_env POLICY_FILE "$POLICY_FILE"
pause "Edit $POLICY_FILE if needed, then press Enter to continue."

# ── Stage 7: doctor ──────────────────────────────────────────────────────
stage "doctor: read-only diagnosis"
say "Running doctor against $GATEWAY_URL (read-only; nothing is written)."
doctor_rc=0
doctor_out=$(run_cli doctor \
  --bundle-manifest "$BUNDLE_MANIFEST" \
  --gateway-token-file "$TOKEN_FILE" \
  --server-config-name "$SERVER_CONFIG_NAME" \
  --profile "$PROFILE" 2>&1) || doctor_rc=$?
printf '%s\n' "$doctor_out"
if grep -qE 'FAIL[[:space:]]+gateway-info' <<<"$doctor_out"; then
  warn "gateway-info failed: the Gateway rejected the URL or token. Fix stage 2 and re-run."
  exit 1
fi
if (( doctor_rc != 0 )); then
  warn "doctor exited $doctor_rc — expected before the first deploy (the endpoint is not provisioned yet)."
  note "Review the FAIL lines above; if any are unexpected, fix them and re-run this wizard."
fi

# ── Stage 8: plan ────────────────────────────────────────────────────────
stage "plan: what apply will do"
say "Running plan (read-only; nothing is written)."
plan_args=(plan
  --bundle-manifest "$BUNDLE_MANIFEST"
  --bundle-zip "$BUNDLE_ZIP"
  --gateway-token-file "$TOKEN_FILE"
  --server-config-name "$SERVER_CONFIG_NAME"
  --profile "$PROFILE"
  --policy-file "$POLICY_FILE")
if [[ -n "$PERMISSIONS_FILE" ]]; then
  plan_args+=(--server-config-permissions-file "$PERMISSIONS_FILE")
fi
plan_rc=0
run_cli "${plan_args[@]}" || plan_rc=$?
if (( plan_rc != 0 )); then
  warn "plan exited $plan_rc (3 = a BLOCKED line: fix the cause above, usually the Module or a foreign project)."
  exit 1
fi
if ! confirm "Proceed to apply?"; then
  say "Stopped before any write."
  exit 0
fi

# ── Stage 9: apply ───────────────────────────────────────────────────────
stage "apply: write the deployment"
warn "apply writes to the Gateway and has no undo; --backup-dir is the only local copy."
say "Backup directory: $BACKUP_DIR"
if ! confirm "Apply now?"; then
  say "Stopped before any write."
  exit 0
fi
apply_args=(apply
  --bundle-manifest "$BUNDLE_MANIFEST"
  --bundle-zip "$BUNDLE_ZIP"
  --gateway-token-file "$TOKEN_FILE"
  --profile "$PROFILE"
  --bundle-project "$BUNDLE_PROJECT"
  --server-config-name "$SERVER_CONFIG_NAME"
  --policy-file "$POLICY_FILE"
  --backup-dir "$BACKUP_DIR")
if [[ -n "$PERMISSIONS_FILE" ]]; then
  apply_args+=(--server-config-permissions-file "$PERMISSIONS_FILE")
fi
if [[ "$PROVISION_SECURITY_LEVELS" == yes ]]; then
  apply_args+=(--provision-security-levels)
fi
if [[ "$CREATE_RUNTIME_TOKEN" == yes ]]; then
  apply_args+=(--create-runtime-token --runtime-token-file "$RUNTIME_TOKEN_FILE")
fi
apply_rc=0
run_cli "${apply_args[@]}" || apply_rc=$?
if (( apply_rc != 0 )); then
  warn "apply exited $apply_rc (1 = a write or verification failed; 3 = nothing was written)."
  exit 1
fi

# ── Stage 10: verify ─────────────────────────────────────────────────────
stage "verify: final check"
say "Running verify (apply already ran the verify sequence; this is the closing confirmation)."
verify_rc=0
run_cli verify \
  --bundle-manifest "$BUNDLE_MANIFEST" \
  --gateway-token-file "$TOKEN_FILE" \
  --server-config-name "$SERVER_CONFIG_NAME" \
  --profile "$PROFILE" || verify_rc=$?
if (( verify_rc != 0 )); then
  warn "verify exited $verify_rc — see the FAIL lines above."
  exit 1
fi

finish
say "MCP endpoint: $GATEWAY_URL/data/mcp/$SERVER_CONFIG_NAME"
note "Point your MCP client at that URL. Re-run verify after every Gateway restart."
