{
  "schemaVersion": 1,
  "name": "configurator",
  "permissions": [
    "READ",
    "CONFIG"
  ],
  "tools": [
    "bundle_info",
    "tag_browse",
    "tag_query",
    "tag_read",
    "tag_get_config",
    "udt_type_list",
    "udt_type_get"
  ]
}
